[default]
workshop = [
    "450814997",  # CBA_A3
    "463939057", # ACE
    "2369477168", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []

[previews]
extends = "default"
mission = "Previews.VR"
parameters = ["-name=Previews"]