name = "MOD_TITLE"
author = "DartRuffian"
prefix = "MOD_PREFIX"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_MOD_PREFIX.png",
    "logo_MOD_PREFIX_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"